name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      master_doc:
        description: "Master document to use"
        required: true
        type: string
        default: "src/index.txt"
      format:
        description: "Master document format"
        required: true
        type: choice
        options:
          - markdown
          - rst
          - latex
        default: rst

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.sha.outputs.value }}
      now: ${{ steps.now.outputs.value }}
    steps:
      - uses: actions/checkout@v4
      - id: sha
        run: echo "value=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - id: now
        run: echo "value=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
  odt:
    runs-on: ubuntu-latest
    needs:
      - setup
    steps:
      - uses: actions/checkout@v4
      - uses: docker://pandoc/core:3.5
        with:
          # noinspection UndefinedParamsPresent
          args: >-
            --standalone
            --citeproc
            --metadata-file=metadata.yaml
            --metadata="date:${{ needs.setup.outputs.now }}"
            --from=${{ github.event.inputs.format || 'rst' }}
            --to=odt
            --output=build-artifact.odt
            ${{ github.event.inputs.master_doc || 'src/index.txt' }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ needs.setup.outputs.sha }}.odt
          path: build-artifact.odt
